### PR TITLE
Use brotli v1.1.0

### PR DESCRIPTION
**Pull request by PikachuEXE**
https://github.com/google/brotli/releases/tag/v1.1.0

### CODE REVIEW

**Comment by miyucy** [comment]
Thanks for update! Should I release this changes? (asap)

**Comment by PikachuEXE** [comment]
Why not :3

**Comment by miyucy** [comment]
Ah, sorry... ok, I'll release at night. (maybe 3-5hrs later)

**Comment by miyucy** [comment]
Hi, sorry for delay. I just push new version. 

> last release was 3 years ago

oh... 🤦

**Pull request merged**
